### ISSUE TITLE
Digest Schema

### ISSUE THREAD

**Issue by mster** [nick-nuti/Backup-Program#8]
Notes:
- Solidify JSON digest schema i.e.: time, permissions, etc.
- Consider:
   - Locked files
   - Hidden files
   - Uniform file permissions (macOS/Windows/Linux)

**Comment by mster** [comment]
Closed by #13

**Comment by nick-nuti** [comment]
Possible future space-saving optimizations:
- Convert "timeLastWritten" and "size" from int64_t to hexadecimal to save 2 characters per entry on average (possibility to save even more)
- Find a way to reduce "path" character length

**Comment by mster** [comment]
Removing "writable" field because it serves no purpose.
